name: Deploy Platformatic application to the cloud
on:
  pull_request:
    paths-ignore:
      - 'docs/**'
      - '**.md'
  workflow_dispatch:
    inputs:
      label:
        description: "Preview Label"
        required: true
        default: ""

jobs:
  build_and_deploy:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    env:
     PORT: 3043 
     PLT_SERVER_HOSTNAME: 127.0.0.1 
     PLT_SERVER_LOGGER_LEVEL: info 
     PLT_GIDDY_BARBARIAN_DATABASE_URL: ${{ secrets.PLT_GIDDY_BARBARIAN_DATABASE_URL }}
     DEPLOY_SERVICE_HOST: https://plt-development-deploy-service.fly.dev 

    steps:
      - name: Checkout application project repository
        uses: actions/checkout@v3
      - name: npm install --omit=dev
        run: npm install --omit=dev
      - name: Deploy project
        id: deploy-project
        uses: platformatic/onestep@latest
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          platformatic_workspace_id: ${{ secrets.PLATFORMATIC_DYNAMIC_WORKSPACE_ID }}
          platformatic_workspace_key: ${{ secrets.PLATFORMATIC_DYNAMIC_WORKSPACE_API_KEY }}
          platformatic_config_path: ./platformatic.runtime.json
          label: ${{ github.event.inputs.label }}
    outputs:
      deployment_id: ${{ steps.deploy-project.outputs.deployment_id }}
  calculate_risk:
    env:
      DEPLOY_SERVICE_HOST: https://plt-development-deploy-service.fly.dev 
    permissions:
      contents: read
      pull-requests: write
    needs: build_and_deploy
    runs-on: ubuntu-latest
    steps:
      - name: Calculate risk
        uses: platformatic/onestep/actions/calculate-risk@latest
        if: github.event_name == 'pull_request'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          platformatic_workspace_id: ${{ secrets.PLATFORMATIC_DYNAMIC_WORKSPACE_ID }}
          platformatic_workspace_key: ${{ secrets.PLATFORMATIC_DYNAMIC_WORKSPACE_API_KEY }}
          platformatic_deployment_id: ${{ needs.build_and_deploy.outputs.deployment_id }}
